# This is a basic workflow to help you get started with Actions

name: NotionJAM

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 21 * * *" # daily
  push:
    branches: [master, main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: notion-jam
        uses: victornpb/notion-jam@v0.0.10
        with:
          NOTION_SECRET: ${{ secrets.NOTION_SECRET }}
          NOTION_DATABASE: https://www.notion.so/elenaelly/f0061c6decb84762ba38ed29a764ae3d?v=b1e6c77dbc154166886908e12bde25fd
          FILTER_PROP: status
          FILTER_VALUES: "Завершен"
          ARTICLE_PATH: /{title}/README.md
          ASSETS_PATH: ./
          PARALLEL_PAGES: 25
          PARALLEL_DOWNLOADS_PER_PAGE: 3
          DOWNLOAD_IMAGE_TIMEOUT: 30
          SKIP_DOWNLOADED_IMAGES: true
          DOWNLOAD_FRONTMATTER_IMAGES: true
      
      - name: Save changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit changes
